# Generated by Django 5.2.2 on 2025-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_visitorvehicleregistration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorvehicleregistration',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
