# Generated by Django 5.2.2 on 2025-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_visitorvehicleregistration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitybooking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
