# Generated by Django 5.2.2 on 2025-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_amenitybooking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitybooking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
