# Generated by Django 5.2.2 on 2025-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_amenitybooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitybooking',
            name='usage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
