# Generated by Django 5.2.2 on 2025-08-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_amenitybooking_usage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='apartments.resident'),
        ),
    ]
