# Generated by Django 5.2.2 on 2025-09-05 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_apartmenttransferhistory_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttransferhistory',
            name='transfer_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
