# Generated by Django 5.2.2 on 2025-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_alter_apartmenttransferhistory_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitybooking',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
