# Generated by Django 5.2.2 on 2025-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_amenitybooking_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitybooking',
            name='fee',
        ),
        migrations.AddField(
            model_name='amenity',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
