# Generated by Django 5.2.2 on 2025-09-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_remove_amenitybooking_fee_amenity_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='apartments.apartment'),
        ),
    ]
