# Generated by Django 5.2.2 on 2025-09-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_amenity_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='apartment',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='apartments.resident'),
        ),
    ]
