# Generated by Django 5.2.2 on 2025-09-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_remove_amenity_apartment_paymenttransaction_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apartments.apartment'),
        ),
    ]
